### ISSUE TITLE
[design] Requirements error?

### ISSUE THREAD

**Issue by gramai** [UPB-FILS/alf#11]
I believe the POSITION statement in the photo shown bellow should actually be LOCATION statement. If I am wrong, could you please add the definition for POSITION?
![image](https://user-images.githubusercontent.com/33946557/53812852-fa4adb00-3f64-11e9-99a6-984ba09c4cde.png)

Thanks!

**Comment by JStudent97** [comment]
Thank you for pointing it out. Fixed it

**Comment by gramai** [comment]
Also, I am a little bit confused about the formatting of the parameters in the .dsn file. Are they separated by ',' or \s or both? 
The example shows:
"""
& Move
LOCATION: 200, 200
COMMAND_WITH_ERROR  
DRAW_LINE: location 300, 350
"""
But the rest of the documentation shows no ','. 
Thanks

**Comment by JStudent97** [comment]
There should be no comma. I will do a full review this evening , and try to correct all these little mistakes. I appreciate your help :)

**Comment by JStudent97** [comment]
Ok, I have done some small corrections here and there. I will leave this issue open for now. If you find some other problems(regarding the enunciation and the examples) please feel free to leave a message here and I will look into it.

**Comment by gramai** [comment]
Of course, thank you!
