### ISSUE TITLE
If someone can help me with these errors i would be thankful.

### ISSUE THREAD

**Issue by Crastem13** [UPB-FILS/alf#16]
And i do not know why the Reverse One Works but Revese doesn't work. I put the same numbers in my terminal that the checker tries and they are reversed. 
And Verifying Power Negative...............................error (0p) what does this ask from me? One hint,please?
Thank you for your time.

**Comment by RaduNicolaeEduard** [comment]
### Reversed:
You are sorting the whole string from high to low
But you are supposed to reverse each element

### Author/Help:
In VmChecker it seems that your code  does not output anything, check if it the output is exactly the same as [This](https://github.com/UPB-FILS/alf/blob/master/Devoir/calculator/verify/calculator/1_folder.a_author.out) , where it says _ALF_ there should be your name ( you might have an extra line or something else)

**Comment by Crastem13** [comment]
Thank you. It was a stupid extra line. And at reversed now i understand what i have to do :D
