### ISSUE TITLE
vmexecutor exitcode 1 (error)

### ISSUE THREAD

**Issue by Crastem13** [UPB-FILS/alf#17]
What does this mean? I actually did change only a few spacing problems in the code and now it does not check it anymore. And 5 mins ago it worked.

**Comment by alexandruradovici** [comment]
What si your username for the website?

**Comment by Crastem13** [comment]
Ionut-Teodor Badea is my name. But now it works again. Sorry for putting the same issue as a collegue but when i read my collegue's issue it did not tell a solution.
