### ISSUE TITLE
[design] checker

### ISSUE THREAD

**Issue by diana-ghindaoanu** [UPB-FILS/alf#18]
When I try to test my homework locally, the checker validates many tests that I have not done yet, but when I load the vmchecker, I don't pass some tests. The bigger problem is that I can not see the differences between my file and yours because they are pretty compressed.
What can I do to see all the differences?

I uploaded an image to be a bit clearer.
![Capture](https://user-images.githubusercontent.com/47796147/54156124-40fd7100-444e-11e9-97e9-43d4dfdef4fc.PNG)

**Comment by alexandruradovici** [comment]
Please read #14
