### ISSUE TITLE
[calculator] Error cowsay

### ISSUE THREAD

**Issue by diana-ghindaoanu** [UPB-FILS/alf#2]
I get this error every time I try to use cowsay, but i followed the same steps as before. Am I missing something?
![capture](https://user-images.githubusercontent.com/47796147/53351894-8720e380-392a-11e9-916e-2ac7d02d1a5f.PNG)

**Comment by alfredrogoveanu** [comment]
Had the same issue, save it locally:

`npm install cowsay --save`

**Comment by diana-ghindaoanu** [comment]
Still not working...

**Comment by alexandruradovici** [comment]
Please read the error: npm says it cannot install cowsay as it has an error in the package.json file. Copy and paste the contents of the file here [1] and look at the errors.

[1] https://jsonformatter.curiousconcept.com/

**Comment by alexandruradovici** [comment]
@diana-ghindaoanu does it work now?

**Comment by diana-ghindaoanu** [comment]
Yes
