### ISSUE TITLE
<calculator> vmcheker

### ISSUE THREAD

**Issue by Tamina26** [UPB-FILS/alf#20]
I have a  problem  when i put the homework in the vmchecker they give me the operations are not working,it tells me that is undefined.  In the node js is working,but only when i take the operations separately,in different files , if i put all the operations in a single file it gives the result,but it says also that is undefined.
![Capture](https://user-images.githubusercontent.com/61236017/76218875-a03ac080-621d-11ea-9bc2-b299337bc61c.PNG)
![Capture2](https://user-images.githubusercontent.com/61236017/76218880-a16bed80-621d-11ea-91d6-77a538b2a888.PNG)
[use.docx](https://github.com/UPB-FILS/alf/files/4306959/use.docx)

If there is any solutions

**Comment by alexandruradovici** [comment]
You are using pop twice, that destroys the arguments list.
