### ISSUE TITLE
Homework instructions not clear

### ISSUE THREAD

**Issue by samedFari** [UPB-FILS/alf#22]
![image](https://user-images.githubusercontent.com/62061363/76418399-3cdc9a00-63a7-11ea-863b-690796c2d934.png)

1st dilemma: The 3rd coordonates indicates a 90 degrees rotation; what does that mean? Using the trigonometric circle, that indicates it is facing upwards? Am i right? So if the robot moves forward.. 2 pixels let's say, with a 90 degree rotation(initial rotation), the Y coordinate should increment , right? While the given example shows the X coordinate modifying:

![image](https://user-images.githubusercontent.com/62061363/76418766-e2900900-63a7-11ea-8a0e-84da22ef98c5.png)

2nd dilemma:
![image](https://user-images.githubusercontent.com/62061363/76418905-2256f080-63a8-11ea-92e7-86bc700151f8.png)

The error message is wrong here. Forward command actually takes only 1 parameter. The error message indicates it takes 2. 

3rd dilemma: When does the 'Y' coordinate modifies?
![image](https://user-images.githubusercontent.com/62061363/76419355-dce6f300-63a8-11ea-9cb4-66a52dd5c9da.png)
![image](https://user-images.githubusercontent.com/62061363/76419395-ea9c7880-63a8-11ea-89a9-9ce9a8d71cc5.png)

again, using both the triconometric circle and the results from
![image](https://user-images.githubusercontent.com/62061363/76419486-1a4b8080-63a9-11ea-820d-ece02377feec.png)

I deduced that if the rotation angle is between 120 and 60 degrees when we move the robot with forward let's say..only the 'X' should be modified. In the 2 pictures from above, we see that at a 84 degree rotation angle, the 'Y' coordinate is also modified ..with 1?.. it shouldn't modify at all... and even if it should have...why with only 1 pixel (if the move is made with 6 pixels)? 
* I use quoted x and y because, using trigonometric circle logic, they should be inverted

In the circle.s test, i see that with FORWARD 1, we increment both X and Y(depending on the rotation angle) with only 1.  

I would appreciate some more indications

**Comment by samedFari** [comment]
Thank you for taking your time to respond..not cool :)

So i figured some of the stuff myself in the end (if any1 else encounters the same issues):

1st dilemma:
 0 degrees rotation means the robot is facing upwards . At 90 degrees rotation (default rotation angle), the robot **is facing RIGHT**. So if he advances (turned 90 degrees)  **only x coordinate increases.** . In other words, with the default rotation of 90 degrees, we are not turning in a trigonometric direction but **clockwise**!  However, another problem pops up now : the command 'turn' rotates the robot in **a trigonometric direction**. I think we should stick to only 1 rotation direction (clockwise/trigonometric).

3rd dilemma:
When we move the robot, (depending on the rotation) we are moving on both axes (x and y). So in order to calculate the distance the robot moves on each axe we have to use the **right triangle's properties**. By calculating the 2 catheti we can find the new coords (every cathetus represents the incremental on 1 axe) , while the distance we get as input (from forward,backward commands) is our hypotenuse. 

2nd dilemma: altho the error is still there, you guys can just write your code properly and you should pass the tests

good luck:)

**Comment by alexandruradovici** [comment]
> Thank you for taking your time to respond..not cool :)

Sorry for the delay, somehow this slipped our mind.

> 
> So i figured some of the stuff myself in the end (if any1 else encounters the same issues):
> 
> 1st dilemma:
> 0 degrees rotation means the robot is facing upwards . At 90 degrees rotation (default rotation angle), the robot **is facing RIGHT**. So if he advances (turned 90 degrees) **only x coordinate increases.** . In other words, with the default rotation of 90 degrees, we are not turning in a trigonometric direction but **clockwise**! However, another problem pops up now : the command 'turn' rotates the robot in **a trigonometric direction**. I think we should stick to only 1 rotation direction (clockwise/trigonometric).

You found a bug here, the calculation is wrong. The robot should be at 0, 0, 90 and the movement is wrong, we will fix the checker.

> 
> 3rd dilemma:
> When we move the robot, (depending on the rotation) we are moving on both axes (x and y). So in order to calculate the distance the robot moves on each axe we have to use the **right triangle's properties**. By calculating the 2 catheti we can find the new coords (every cathetus represents the incremental on 1 axe) , while the distance we get as input (from forward,backward commands) is our hypotenuse.

Same as 1.

> 
> 2nd dilemma: altho the error is still there, you guys can just write your code properly and you should pass the tests

Will fix.

> 
> good luck:)

**Comment by samedFari** [comment]
so we will be using trigonometric circle logic in order to rotate and to calculate the movement of the robot?

**Comment by alexandruradovici** [comment]
Yes

**Comment by alexandruradovici** [comment]
Fixed
