### ISSUE TITLE
[design] checker issue

### ISSUE THREAD

**Issue by diana-ghindaoanu** [UPB-FILS/alf#23]
When I try to test the homework, both locally and vmchecker, the checker gets stuck in the "if else" test and stops checking, though I didn't even write that statement. Is there a problem with the checker or maybe I did something wrong?

**Comment by alexandruradovici** [comment]
I think you might have an infinte loop. Try the test manually and see what it does.

**Comment by JStudent97** [comment]
Inside the  if_else.dsn there is a 'WHILE' , which might be the cause of your infinite loop. Maybe you have code written for while and that's why u get the infinite loop

**Comment by diana-ghindaoanu** [comment]
Ok, I'll check again, thanks.
