### ISSUE TITLE
[design] loop

### ISSUE THREAD

**Issue by diana-ghindaoanu** [UPB-FILS/alf#26]
'IF' statements can be imbricated in a WHILE/FOR statement and vice versa?

**Comment by GeorgeTudose** [comment]
https://github.com/UPB-FILS/alf/blob/master/Devoir/design/verify/design/3_loop/if_else.dsn

Yes, if can be inbricated in a WHILE/FOR

I am almost sure that there is no WHILE/FOR in any IF.

**Comment by diana-ghindaoanu** [comment]
Thanks :)
