### ISSUE TITLE
Homework 01: Calculator, A Small Error :)

### ISSUE THREAD

**Issue by andy-ovidiu-matei-buruiana** [UPB-FILS/alf#3]
Good evening, I noticed that in the online checker there is an error for the "Negative power" verification, in the way that despite the result being the same until the n-th decimal, the checker has a n+1-th decimal that Math.pow( ) doesn't reach, thus resulting in an error.

   Same issue with the offline checker.

**Comment by ZamfirAndreiPaul** [comment]
I also had this error in the Linux checker. After an update to NodeJS in version 12.16.1 the problem was solved.

**Comment by diana-ghindaoanu** [comment]
The result of this operation depends on the node version you are using. When testing the homework on vmchecker you will see that the problem will be automatically solved.
