### ISSUE TITLE
Various errors found in tests

### ISSUE THREAD

**Issue by alfredrogoveanu** [UPB-FILS/alf#3]
- The _Author_ and _Display_ tests are stuck with a different author name;
- On the OCW it says that the _maximum_ and _minimum_ ops need at least **one** parameter, meanwhile the error tests for them say the ops need at least **two** parameters.

https://imgur.com/vttUVvs

Also, Vmchecker doesn't work: 

> Coada temelor ce urmează să fie testate
{
    "errorTrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/vmchecker/websutil.py\", line 239, in get_test_queue_contents\n    look_for_keys=False)\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/client.py\", line 348, in connect\n    server_key)\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/client.py\", line 635, in missing_host_key\n    raise SSHException('Server %r not found in known_hosts' % hostname)\nSSHException: Server 'checker.cs.pub.ro' not found in known_hosts\n"
}

**Comment by alexandruradovici** [comment]
Looking into the checker.

We reported the issue to vmchecker, hope to fix it soon.

**Comment by JStudent97** [comment]
I fixed the errors found in tests. Hopefully vmchecker will be up and running soon enough. Until then you can test locally your homework.

**Comment by alexandruradovici** [comment]
@alfredrogoveanu please confirm it works

**Comment by alfredrogoveanu** [comment]
I can confirm it works. Many thanks!

**Comment by JStudent97** [comment]
Vmchecker is working and it's up to date with the tests.
