### ISSUE TITLE
[alf language]

### ISSUE THREAD

**Issue by diana-ghindaoanu** [UPB-FILS/alf#31]
1. Comentariile pot aparea oriunde in cod? Am citit ca ele se pot intinde pe mai multe linii, dar totodata ca daca nu avem regula pentru comentarii, putem pur si simplu sa ignoram prima linie. In cazul in care ar fi pe mai multe, nu prea imi dau seama cum sa cresc numarul liniei daca eu sar peste ele.

2. La inceput ni se spune ca toate nodurile au node_id si line si se da o lista de node_id-uri, dar in exemple toate au "id". Sunt 2 lucruri diferite? Si identifier nu pare a fi inclus in lista de node_ids. (sau nu imi scapa mie?)

3. Numele functiilor pot include "_"?
Daca am function f() =>expression; inseamna ca expression este continutul functiei?

4. Link-urile catre exemple nu functioneaza...

**Comment by alexandruradovici** [comment]
> Comentariile pot aparea oriunde in cod? Am citit ca ele se pot intinde pe mai multe linii, dar totodata ca daca nu avem regula pentru comentarii, putem pur si simplu sa ignoram prima linie. In cazul in care ar fi pe mai multe, nu prea imi dau seama cum sa cresc numarul liniei daca eu sar peste ele.

Da, pot fi puse oriunde in fisier. Fiecare fisier are insa un comentariu pe prima linie, iar daca nu ai regula pentru comentarii, poti sari prima linie si vor trece testele fara comentarii in alta pozitie.

> La inceput ni se spune ca toate nodurile au node_id si line si se da o lista de node_id-uri, dar in exemple toate au "id". Sunt 2 lucruri diferite? Si identifier nu pare a fi inclus in lista de node_ids. (sau nu imi scapa mie?)

node_id e numele din exemplu, acesta trebuie inlocuit cu numele nodului. Da, idenificatorul este un nod.

> Numele functiilor pot include "_"?
Daca am function f() =>expression; inseamna ca expression este continutul functiei?

Pot sa aiba _. Da, conitnutul functiei este o singura expresie (si doar expresie). Este echivalent cu return expresie.

> Link-urile catre exemple nu functioneaza...

Am rezolvat

**Comment by diana-ghindaoanu** [comment]
Multumesc!
