### ISSUE TITLE
Repeat no end issue.

### ISSUE THREAD

**Issue by ZamfirAndreiPaul** [UPB-FILS/alf#42]
Here is the file .s :
![2038311eb89e960e7d22bfc8e9dee5cf](https://user-images.githubusercontent.com/56279630/77249170-e9d8d180-6c47-11ea-96f6-4df19795dd25.png)

And here is the output : 
![fec2edd0359ee3900e28c713f4f3d646](https://user-images.githubusercontent.com/56279630/77249173-f2310c80-6c47-11ea-872b-1ff06e126f10.png)

Why error line is 5? Because repeat is on line 2.

**Comment by RaduNicolaeEduard** [comment]
It is the last empty line of the file
Check out this Thread -> #25

**Comment by ZamfirAndreiPaul** [comment]
And this error display the line before end?

**Comment by RaduNicolaeEduard** [comment]
I do not understand the question.

**Comment by ZamfirAndreiPaul** [comment]
Does the error display at the last line of the file? It was no longer logical to show the line where the repeat is.

**Comment by RaduNicolaeEduard** [comment]
Yup at the last line of the file

**Comment by ZamfirAndreiPaul** [comment]
Thanks Nicolae.
