### ISSUE TITLE
without_end.s.out , circle and rectangle tests 

### ISSUE THREAD

**Issue by philip31** [UPB-FILS/alf#45]
i have a problem with " without_end.s.out" and with the circle and rectangle tests

this is my output for "without_end.s"

![Screenshot (147)](https://user-images.githubusercontent.com/61235963/77254130-d6d5f980-6c67-11ea-9807-5796070d07ad.png)

this is what the checker sees

![Screenshot (148)](https://user-images.githubusercontent.com/61235963/77254090-96767b80-6c67-11ea-80ec-55a04eb232b8.png)

Also for the circle and rectangle tests, there is a small difference in aproximation (i want to point out that i use math.round after multilpying sin/cos's results with the forward/backward's values)

![Screenshot (149)](https://user-images.githubusercontent.com/61235963/77254093-9aa29900-6c67-11ea-976f-be962aa23fed.png)

**Comment by alexandruradovici** [comment]
Please use Math.round only once after computing everything.

**Comment by philip31** [comment]
thanks, it worked for circle, but i still have problems with rectangle and "without_end.s"

**Comment by alexandruradovici** [comment]
Verify your code.
