### ISSUE TITLE
Could not parse Jison grammar

### ISSUE THREAD

**Issue by dragossolca** [UPB-FILS/alf#47]
Hello! I am trying to redo the last lab and I get this error

![image](https://user-images.githubusercontent.com/56224261/77339604-b1fb8800-6d34-11ea-8237-c5e2de854589.png)

I have tried deleting it and installing it once again. It didn't act up before. 
Could you help me, please?

**Comment by diana-ghindaoanu** [comment]
Hi!

Please put the .y file first (jison ex1.y ex1.l).

**Comment by dragossolca** [comment]
Thanks a lot! I see why now.
