### ISSUE TITLE
I have a question about the lab ?

### ISSUE THREAD

**Issue by AlexandruCristian2312** [UPB-FILS/alf#48]
Good evening ! I saw in my lab situation that I have a lot of zero marks! From now on I must participate with the group 1221F I belong to, it is mandatory, right? Because before we go online,I participate with the CTI group, at that time i was to the job , but now i'm home! Now being home I will respect the program! However, why  i wasn't  noted on those labs? I know that one online was missing, but the other?

**Comment by diana-ghindaoanu** [comment]
Buna!
Pentru laboratorul 5 a fost greseala mea, am uitat sa iti trec nota, am rezolvat acum. La laboratorul 4 nu ai fost prezent, mi-ai trimis doar spre seara rezolvarea si regula este ca toata lumea trebuie sa si participe la laborator si sa trimita rezolvarile in intervalul respectiv. Pentru laboratorul 2 nu avem listele de prezenta ca sa putem verifica acum, dar daca stii ca ai fost prezent, o sa rezolvam cand ne intoarcem la facultate.
