### ISSUE TITLE
[calculator] Homework 1 requirements

### ISSUE THREAD

**Issue by gramai** [UPB-FILS/alf#5]
Hello. 
I believe there is an error in Homework 1.
In the "Operations" Table, "Example" section, for the "unique" operation, we have:
`node main.js uniqe 2 4 3 5 6 7 3` when there shoud be `node main.js unique 2 4 3 5 6 7 3` (mind the missing "u").

Thanks

**Comment by JStudent97** [comment]
FIxed it. Thank you for letting us know.
