### ISSUE TITLE
have no access to homework-link

### ISSUE THREAD

**Issue by AhmedJebara** [UPB-FILS/alf#5]
Continutul enuntului il puteti gasi la urmatorul link:
link enunt

===>>
404 Not Found
The requested URL /ui/TODO was not found on this server.

Apache/2.2.22 (Debian) Server at vmchecker.cs.pub.ro Port 443

**Comment by ZamfirAndreiPaul** [comment]
Hello.  This link not work. The corect link is : https://ocw.cs.pub.ro/courses/alf/teme/tema_en_1
Or if you want the link in French : https://ocw.cs.pub.ro/courses/alf/teme/tema1

Success at homework.
