### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by alexandra2607** [UPB-FILS/alf#55]
How can I fix it?

alexandra@LAPTOP-7RVJNJUD:/mnt/c/Users/Andra/Desktop/alf-master/Devoir/alf$ make -f Makefile.checker
npm WARN alf@1.0.0 No repository field.
Your main file is main.js
The author is Andra
./run_all.sh: line 52: jshint: command not found
Please review your code, you have jshint errors
Tests:  0 / 0
Points: 0
Mark without penalities: 0
alexandra@LAPTOP-7RVJNJUD:/mnt/c/Users/Andra/Desktop/alf-master/Devoir/alf$

**Comment by cristinagavanescu** [comment]
Have you tryied run this command in node terminal? 
npm install -g jshint
