### ISSUE TITLE
Grammar conflict

### ISSUE THREAD

**Issue by MicuSebastian** [UPB-FILS/alf#58]
I'm trying to solve the variable_with_expression.alf and after i created the statement with expression, some grammar conflicts encountered. The output is correct, but on checker it warns me that i have grammar issues. I uploaded my version with expression commented. Can I get a hint on how i should create it or replace it?

**Comment by alexandruradovici** [comment]
Do you have %left or %right options for all the operators in the grammar?

**Comment by MicuSebastian** [comment]
Yes, I added all the operators with %left.

**Comment by alexandruradovici** [comment]
This rule is the problem:
   value '+' value '*' value
This is not a generic rule, it is written to pass the actual tests. For the expression parser, take a lok at the lab examples.

Newlines should be ignored, they are not part of the language.

**Comment by MicuSebastian** [comment]
I know, I only tried this to check if I have any conflicts. I will look again at the lab examples.  Thank you!
