### ISSUE TITLE
I have a problem with Real and string , number & logic  tests

### ISSUE THREAD

**Issue by cristinagavanescu** [UPB-FILS/alf#59]
Hello, I have a problem with these tests, caould you give me a hint? I have this error:
Lexical error on line 4: Unrecognized text.

  Erroneous area:
1: #Real and string#
2:
3: 534.534;
4: "this is a text";
^..^

But I have a rule for string values

**Comment by CraciunRAlexandra** [comment]
Did you use the same rule in the lab? (I think it needs to be changed a little) :)
P.S. I'm not very sure, but I'm just trying to give you a tip, you can try to see if it works until a teacher answers  :D

**Comment by cristinagavanescu** [comment]
I have changed it, but no idea why doesn't work, btw, thank you :)

**Comment by sarasolot** [comment]
Try to put float before string in .l file
