### ISSUE TITLE
Homework 1 Author & Help issue

### ISSUE THREAD

**Issue by RaduNicolaeEduard** [UPB-FILS/alf#6]
## VmChecker gives me an error in author and help check
I am sure that this is completely my fault, but i can't wrap my head around this issue ( I just want to go to the bonus exercises :disappointed_relieved:)
These are the errors that VmChecker gives me:

![Annotation 2020-02-29 220216](https://user-images.githubusercontent.com/61273664/75614409-216cc600-5b41-11ea-98d8-5f10132c1e5a.jpg)

And this is what my code does with the help and no arguments command:

![Annotation 2020-02-29 221600](https://user-images.githubusercontent.com/61273664/75614426-4d884700-5b41-11ea-9bcd-7aa7a3457c61.jpg)

**I use 2 console logs to display the help section, and in the package.json the author name is the same as in the help section.**

Thank You in advance for any sollutions :smiley:

**Comment by alexandruradovici** [comment]
You might be missing an empty line. The expected outputs are in verify/calculator in the .out files. Ignore the ALF name, it is replaced by the verifying software.

**Comment by RaduNicolaeEduard** [comment]
Solved it, I had a empty line between the Cowsay and the commands. 
Thank You
