### ISSUE TITLE
Error alf homework 

### ISSUE THREAD

**Issue by CraciunRAlexandra** [UPB-FILS/alf#60]
Hello,  I have an error on several tests (ex:" Unexpected token + in JSON at position 6") and I don't know exactly what it is and where I should go, in the code, to solve it. A little help, please :D

![1bbe0cb0a1367a24877ec2d0a0e250f7](https://user-images.githubusercontent.com/56547343/79069436-d5cc4100-7cd6-11ea-869d-414c3cbd8581.png)

**Comment by alexandruradovici** [comment]
Most probably you are using the JSON.parse function, but give it a parameter that is not a valid json string.
