### ISSUE TITLE
error on the comment rule

### ISSUE THREAD

**Issue by daniciucBianca** [UPB-FILS/alf#61]
![errIDENTIFIERoverTEXT](https://user-images.githubusercontent.com/48835722/79152899-abad7880-7dd5-11ea-8627-47b9bf1f0e2e.PNG)
Heya! I'm trying to do the comment rule so that the other files will run. If the comment receives a token # and a regex expresion and at the end another token # then why is it looking into the IDENTIFIER, when it should take the TEXT exp ?

**Comment by alexandruradovici** [comment]
You have to write a lexer token for the comment, the comment is a token that is not getting to the parser, it is ignored. Basically you need a regular expression for the comment. It is very similar to the string's regular expression, but instead of " you have the # symbol.

**Comment by daniciucBianca** [comment]
That makes sense. Thank you :D
