### ISSUE TITLE
[ sematinc ] VmChecker, Spacing & Symbol Issues

### ISSUE THREAD

**Issue by RaduNicolaeEduard** [UPB-FILS/alf#65]
## VmChecker, Spacing & Symbol Issues
Hello!
I think that my code is generating the JSON files ok with the provided examples

![Annotation 2020-04-25 093049](https://user-images.githubusercontent.com/61273664/80273564-ebc90100-86db-11ea-99eb-ae6035b4db16.jpg)

But I see that VmChecker has the symbol table as an object, the "error_list" is labeled as "errors", the statements array is under an object named script, etc...

![Annotation 2020-04-25 095407](https://user-images.githubusercontent.com/61273664/80273585-0ef3b080-86dc-11ea-90aa-bc6937d7bd33.jpg)
 
And I would like some advice on how to add the symbol elements to the AST tree ( for now I just add symbol : 0  to the tree where it is needed)
I do not understand when it is 0 or 1 or what it is 😅 

Edit: forgot to ask about the spacing, I am separating the JSON file by a tab is this ok?

**Comment by RaduNicolaeEduard** [comment]
Just found a new thing on ocw the symbol table is an object 

![Annotation 2020-04-25 101426](https://user-images.githubusercontent.com/61273664/80273780-dc4ab780-86dd-11ea-89c8-bb0684b6520c.jpg)

but on the provided files it is an array

![Annotation 2020-04-25 101856](https://user-images.githubusercontent.com/61273664/80273835-73b00a80-86de-11ea-89a0-36d19372c087.jpg)

Edit: I now see that the files are updated but there still are some mishaps, the [variable_list.alf.json ](https://github.com/UPB-FILS/alf/blob/master/Devoir/semantic/verify/semantic/1_variable_definition/variable_list.alf.json)has the ast tree empty, the "error_list" is still "errors".

**Comment by alexandruradovici** [comment]
Please update the checker from git, it was changed this week.

**Comment by RaduNicolaeEduard** [comment]
Yup just saw that 
I still have some questions:
 when I stringify the JSON is it spaced by a tab?
and is the [variable_list.alf.json](https://github.com/UPB-FILS/alf/blob/master/Devoir/semantic/verify/semantic/1_variable_definition/variable_list.alf.json) supposed to have the ast.script.statements empty

**Comment by alexandruradovici** [comment]
> Yup just saw that
> I still have some questions:
> when I stringify the JSON is it spaced by a tab?

Tabs and spaces do not matter, we do not verify with diff.

> and is the [variable_list.alf.json](https://github.com/UPB-FILS/alf/blob/master/Devoir/semantic/verify/semantic/1_variable_definition/variable_list.alf.json) supposed to have the ast.script.statements empty

Yes, there are only variable declarations without any attribution. The variable declaration is just to inform the compiler to add a variable to the symbol table, it does  not produce any actions. On the other hand, if you have a declaration with an initial value that will produce an attribution.

**Comment by alexandruradovici** [comment]
> > Yup just saw that
> > I still have some questions:
> > when I stringify the JSON is it spaced by a tab?
> 
> Tabs and spaces do not matter, we do not verify with diff.
> 
> > and is the [variable_list.alf.json](https://github.com/UPB-FILS/alf/blob/master/Devoir/semantic/verify/semantic/1_variable_definition/variable_list.alf.json) supposed to have the ast.script.statements empty
> 
> Yes, there are only variable declarations without any attribution. The variable declaration is just to inform the compiler to add a variable to the symbol table, it does not produce any actions. On the other hand, if you have a declaration with an initial value that will produce an attribution like in this example [simple_with_value.alf.json](https://github.com/UPB-FILS/alf/blob/master/Devoir/semantic/verify/semantic/1_variable_definition/simple_with_value.alf.json)

**Comment by alexandruradovici** [comment]
We updated the homework text, to have errors instead of error_list in the output ast.

**Comment by RaduNicolaeEduard** [comment]
Thanks!
