### ISSUE TITLE
Semantic homework issue

### ISSUE THREAD

**Issue by cristinagavanescu** [UPB-FILS/alf#66]
Hello, i'm trying to understand how to access the variables and i don.t know if my code is ok until now, because i was thinking that the property "type" : "script" should appear in my output file, but doesn't appear , can you give me a hint?

**Comment by alexandruradovici** [comment]
You have to add that property in the symbol table. You have to build the symbol table following these rules:

1. If it is a global symbol (variable, function or type - struct or vector) that is in the main program, not inside a loop, if or a function it goes in to the script symbol table (an object that has type `script`)
2. If it is a local symbol, if it is inside a function, you have to add it to to function's symbol table. That object will have the name `function_$function_name` (where $function_name) is the name of the function, and the type `function`
3. If it is in a loop, it will be in a symbol table with the name while_, for_, do_ followed by the line where the loop is and the type `statements`
