### ISSUE TITLE
Semantic homework

### ISSUE THREAD

**Issue by cristinagavanescu** [UPB-FILS/alf#67]
I have a problem with the "Attr" node, for the tests with struct(for example access struct): i don t know how to take the name of the struct, when i am in the attr node, because the name is in elements from id node, not attr node, so should i try to write the code for this test for id node?

**Comment by alexandruradovici** [comment]
The attribution node has two parameters:
  - to
  - from

Both of them are object. The `to` parameter my be a node of type:
  - identifier - this means that the name of the struct is node.to.title and the type is node.to.type 
  - element_of_array or property - you just have to compute the type for this node and use node.to.type

I assume the name you are looking for is the type (node.to.type) and not the actual name of the struct variable.
