### ISSUE TITLE
prime_numbers.alf.wat question

### ISSUE THREAD

**Issue by DianaScurtu** [UPB-FILS/alf#70]
Hi,
I have a question about the [**prime_numbers**](https://github.com/UPB-FILS/alf/tree/master/Devoir/assembly/verify/assembly/5_loop) test.

In the case of the **not** operator, when should we use the **.eqz** statement?

**Comment by alexandruradovici** [comment]
The .eqz is from the while, I added a comment there. If the exp is false, it will exit jump over the while (br_if).
