### ISSUE TITLE
AFN Question.

### ISSUE THREAD

**Issue by RaduNicolaeEduard** [UPB-FILS/alf#72]
I don't know if this Github page is still active, but I will post an issue anyway :D

I am trying to solve this expression `(aab)* | ba`

![20200531_155931](https://user-images.githubusercontent.com/61273664/83352946-c755e980-a357-11ea-8a47-65ec74ecc8b6.jpg)

So when I read ` ba ` it goes into `S5` but there I have an epsilon that goes into `S2` so I suppose that it can read `baaab`

How can I fix this?

**Comment by alexandruradovici** [comment]
This is a very good question, I think you just found an error in our example.

I would use two final states, one for (aab)* and one for ba, just add an S8.

**Comment by RaduNicolaeEduard** [comment]
Thank You!

**Comment by RaduNicolaeEduard** [comment]
Forgot to say that this was not from your example, I am just making expressions and solving them, so don't look for the error because it's nonexistent :D
